name: Flutter check

on: [push, workflow_dispatch]

jobs:
  setup:
    name: Flutter check
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v1
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter formatter
        run: flutter format lib
  format:
    needs: setup
    if: success()
    name: Flutter formatter
    runs-on: ubuntu-latest
    steps:
      - name: Flutter formatter
        run: flutter format lib
  lint:
    needs: setup
    if: success()
    name: Flutter linter
    runs-on: ubuntu-latest
    steps:
      - name: Flutter linter
        run: flutter analyze lib
  metrics:
    needs: setup
    if: success()
    name: Code Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Run Code Metrics
        run: flutter pub run dart_code_metrics:metrics --reporter=github lib
  summary:
    needs: [format, lint, metrics]
    if: success()
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - name: Summary
        run: echo 'OK'