name: Flutter check

on: [push, workflow_dispatch]

jobs:
  format:
    name: Flutter formatter
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter formatter
        run: flutter format lib

  lint:
    name: Flutter linter
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter pub get
        run: flutter pub get
      - name: Flutter linter
        run: flutter analyze lib

  metrics:
    name: Flutter code metrics
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v3
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Flutter pub get
        run: flutter pub get
      - name: Run Code Metrics
        run: flutter pub run dart_code_metrics:metrics --reporter=github lib
  summary:
    needs: [format, lint, metrics]
    if: success()
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - name: Print summary
        run: echo "OK" >> $GITHUB_STEP_SUMMARY
